#默认使用配置
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 10.10.18.45
    port: 6379
    password: 123456




logging:
  config: classpath:logback-boot.xml


debug: false
---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-jpa
    username: root
    password: 881213
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

