spring:
  datasource:
    username: root
    password: 881213
    url: jdbc:mysql://localhost:3306/springboot-jdbc?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8088
